libraries/get_ssh_ciphers.rb
we originally removed GCM from the cipher chain due to vulnerabilities in OpenSSH. We are adding it back, since any sensible implementation will have had enough time to fix or backport. On top of that, GCM is generally a preferred algorithm. Let's get it back now.
Signed-off-by: Dominik Richter <dominik.richter@gmail.com>
=> add back GCM cipher

libraries/get_ssh_macs.rb
Fixes: #66
See:
* https://stribika.github.io/2015/01/04/secure-secure-shell.html
Signed-off-by: Dominik Richter <dominik.richter@gmail.com>
=> reprioritize etm macs

libraries/get_ssh_kex.rb, spec/recipes/client_spec.rb, spec/recipes/server_spec.rb
Move diffie-hellman-group14-sha1 and diffie-hellman-group-exchange-sha1 to 'weak' KEX mechanisms.
References:
* https://stribika.github.io/2015/01/04/secure-secure-shell.html
* https://github.com/TelekomLabs/chef-ssh-hardening/issues/64
=> remove sha1 key-exchange mechanisms from default

.travis.yml, Gemfile, gemfile.chef-11
for ruby 2.0 and greater, test with chef 11 and 12 (or greater). for ruby 1.9 (or before), don't test chef 12 as it requires ruby 2.0 to work:
https://www.chef.io/blog/2014/11/25/ruby-1-9-3-eol-and-chef-12/
Signed-off-by: Dominik Richter <dominik.richter@gmail.com>
=> bugfix: adjust travis to work with chef12/ruby2

README.md, attributes/default.rb, templates/default/opensshd.conf.erb
We like having a MOTD, so I added these attributes to enable support for that.
=> Adding attributes to enable printing the MOTD.

templates/default/opensshd.conf.erb
Fixed typo in configuration file + removed trailing whitespace
=> fix typo in opensshdconf.erb, remove trailing whitespace

attributes/default.rb, recipes/server.rb, spec/recipes/server_spec.rb, templates/default/opensshd.conf.erb
This is a pull request to close #75.
Ruby is not my most comfortable language and I did quite some copy and pasting, but we pass all the rake tests.
I also tried to ensure the config file would be identical to the current one if the default attributes were used to prevent noise during chef runs after updating the whatever version this ends up in.
=> Allow deny users to be managed from attributes

attributes/default.rb, spec/recipes/server_spec.rb, templates/default/opensshd.conf.erb
=> Make UseDNS configurable

libraries/get_ssh_ciphers.rb, libraries/get_ssh_kex.rb, libraries/get_ssh_macs.rb
Should be the exact equivalent changes made to the puppet repo. closes #77 
Also should we look into chefspec tests for those helpers, or just let serverspec cover it?
=> Modern alogs for Jessie

README.md, attributes/default.rb, templates/default/opensshd.conf.erb
Seems that the concern is similar for tcp and agent, and yet they are configurable.
If I am the only user on my server, and I'm choosing to trust it for agent forwarding, x11 forwarding should not compromise my local system to any greater degree, correct?
=> x11 forwarding should be configurable like tcp and agent forwarding

attributes/default.rb, templates/default/openssh.conf.erb, templates/default/opensshd.conf.erb
Applying the PasswordAuthentication attribute from #102 to openssh.conf.
Not sure if its best to use the same attribute, or have separate attributes for SSH and SSHD?
=> Apply PasswordAuthentication attribute to SSH

README.md, attributes/default.rb, metadata.rb, recipes/client.rb, spec/recipes/client_spec.rb, templates/default/openssh.conf.erb
Disable the experimental client roaming feature to mitigate [this vulnerability](http://undeadly.org/cgi?action=article&sid=20160114142733)
=> Disable experimental client roaming

recipes/server.rb
This should make the ssh-hardening cookbook work properly on ubuntu 15.04 and later.   Currently it freaks out if you try to run it with Vivid or Wily, which have moved to the use of systemd rather than Upstart.
=> Add conditional to cover systemd in Ubuntu 15.04+

README.md
A very simple documentation change.
I realised that the ability to control MaxAuthTries and MaxSessions was actually added almost a year ago, but isn't present in the released v1.10 - could you cut a release, please?
=> Document MaxAuthTries and MaxSessions added in 66e7ebfd

.kitchen.vagrant.yml, .kitchen.yml, .rubocop.yml, .travis.yml, Berksfile, Gemfile, Rakefile, gemfile.chef-11, spec/recipes/server_spec.rb
The bundle install command failed because of the github_changelog_generator 1.10.4. So updated it to github_changelog_generator 1.12.0 and also rubocop to 0.31.0.
Signed-off-by: Patrick Münch <patrick.muench1111@gmail.com>
=> Use new InSpec integration tests

.kitchen.yml, .travis.yml
* activates fedora 23 and 24
* removes ubuntu 15.10 from travis since 16.04 is included
=> activate fedora integration tests in travis

attributes/default.rb
>method access to node attributes (node.foo.bar) is deprecated and will be removed in Chef 13, please use bracket syntax (node["foo"]["bar"])
=> Use bracket syntax in attributes/default.rb

recipes/client.rb, recipes/server.rb, spec/recipes/client_spec.rb, spec/recipes/server_spec.rb
`node.set` causes deprecation warnings in tests (found while writing a cookbook to setup a bastion SSH server).
I changed the specs to `node.normal` because that’s what the ChefSpec readme now [recommends](https://github.com/sethvargo/chefspec#setting-node-attributes) (a change made by the maintainer after getting reports of the same deprecation warnings) and because `node.default` broke tests.
The recipes I changed to `node.default`, which is a little different underneath because default attributes don’t persist and ones set by `node.set`/`node.normal` do. I did this for several reasons:
* The Chef attributes doc [recommends](https://docs.chef.io/attributes.html#attribute-types) using `node.default` as often as possible.
* The Chef Style Guide …
=> Fix deprecation warnings

attributes/default.rb, templates/default/opensshd.conf.erb
This commit parameterises `Banner` and `DebianBanner` in the sshd config
with the attributes `['ssh']['banner']` and `['ssh']['os_banner']` respectively,
though the latter is only supported on Debian family distributions.
Debian based distributions will have `DebianBanner no` set by default
from now on.
=> Parameterise Banner and DebianBanner as attributes

recipes/client.rb, recipes/server.rb
```
Cloning resource attributes for directory[/etc/ssh] from prior resource (CHEF-3694)
Previous directory[/etc/ssh]: /tmp/kitchen/cache/cookbooks/ssh-hardening/recipes/server.rb:56:in `from_file'
Current  directory[/etc/ssh]: /tmp/kitchen/cache/cookbooks/ssh-hardening/recipes/client.rb:26:in `from_file' at 1 location:
```
=> Avoid duplicate resource names because of warnings

.travis.yml, attributes/default.rb
Its basically the open downstream built of SLE: http://www.cio.com/article/3003168/linux/7-things-you-should-know-about-opensuse-leap.html
=> Support for OpenSuse Leap, new enterprise distro of SUSE

.gitignore, .kitchen.vagrant.yml, README.md
- Switching all boxes to the bento (its maintained)
- Removing oracle boxes as there is no reliable source with maintenance for them
- Limiting centos only to the last major versions (the minors are not really important)
Testing on fedora bento boxes is currently broken: https://github.com/chef/bento/pull/709
=> Update kitchen vagrant configuration

README.md, attributes/default.rb, templates/default/opensshd.conf.erb
Path to the Banner File in template 'opensshd.conf.erb' is hard coded to '/etc/ssh/banner.txt'
Not all flavours use this. (for example, CentOS defaults to etc/issue.net)
I have made this configurable by adding an attribute.
=> Configurable SSH Banner File

attributes/default.rb, templates/default/opensshd.conf.erb
Closes https://github.com/dev-sec/chef-ssh-hardening/issues/125
=> Allow to configure ChallengeResponseAuthentication

metadata.rb
In order to see the supported distros in supermarket.
I copied them from os-hardening and added fedora
=> Distro information for supermarket

attributes/default.rb, templates/default/opensshd.conf.erb
Closes https://github.com/dev-sec/chef-ssh-hardening/issues/116
=> Allow login grace time to be configurable

Berksfile, README.md, recipes/server.rb, spec/recipes/server_spec.rb
=> Removal of deprecated authorized_keys handling

spec/spec_helper.rb
```
WARNING: you must specify a platform and platform_version to your ChefSpec Runner and/or Fauxhai constructor, in the future omitting these will become a hard error
```
=> Get rid of chefspec/fauxhai warnings in the unit tests

README.md, attributes/default.rb, recipes/server.rb, spec/recipes/server_spec.rb
=> Bugfix: sshd listens on IPv6 interface if enabled

Rakefile
as changelog generator does not work on the
forks without this config
=> Project data for changelog generator

attributes/default.rb, spec/recipes/client_spec.rb, spec/recipes/server_spec.rb, templates/default/openssh.conf.erb, templates/default/opensshd.conf.erb
=> Send and Accept locale environment variables

.kitchen.vagrant.yml, .kitchen.yml, Berksfile, test/fixtures/cookbooks/test/metadata.rb, test/fixtures/cookbooks/test/recipes/default.rb
They produce broken builds and we do not need them anymore:
https://travis-ci.org/dev-sec/chef-ssh-hardening/jobs/201236096
In the same time we need to run apt-get update at the start of chef-run
as ubuntu does not have any apt repo information. This is the reason
for introduction of test cookbook.
=> Removal of apt/yum cookbooks from tests

README.md, attributes/default.rb, spec/recipes/client_spec.rb, spec/recipes/server_spec.rb, templates/default/openssh.conf.erb, templates/default/opensshd.conf.erb
Add support for extra configuration options at the end of the config files for override support.
This assists with the flexibility issue discussed in #89 
```
default['ssh-hardening']['ssh']['server']['extras'].tap do |extra|
extra['#Some Comment'] = 'Heres the Comment'
extra['AuthenticationMethods'] =  'publickey,keyboard-interactive'
end
```
The block syntax swap is somewhat opinionated, but is more readable for long hash's
=> Add Support for Extra Configuration Options

README.md, attributes/default.rb, spec/recipes/server_spec.rb, templates/default/opensshd.conf.erb
Hi,
this propposed change allow to have configured a custom authorized key file path for an ssh server.
Thanks.
Lubomir Kacalek
=> Authorized keys custom path

.rubocop.yml, .travis.yml, Gemfile, Rakefile, attributes/default.rb, libraries/devsec_ssh.rb, metadata.rb, recipes/client.rb, recipes/default.rb, recipes/server.rb, recipes/unlock.rb, spec/libraries/devsec_ssh_spec.rb, spec/recipes/client_spec.rb, spec/recipes/default_spec.rb, spec/recipes/server_spec.rb, spec/recipes/unlock_spec.rb, spec/shared_examples_crypto.rb, spec/spec_helper.rb
Chef 13 is also using ruby 2.4.1 in the omnibus packages
There are problems with Chef 13.1 in the chefspec tests. The builds are getting stucked without any specific reason. I'll investigate this further...
=> CI: update to ruby 2.4.1 and gem update

.rubocop.yml
as chef 12.5.1, which we still support, is shipped with ruby 2.1
Signed-off-by: Artem Sidorenko <artem@posteo.de>
=> Running rubocop in the 2.1 mode

attributes/default.rb
Since ohai v13.0.0, the attribute "platform_family" for Amazon Linux retrieves "amazon" instead of "rhel", causing the cookbook to fail. (Issue #180)
To get it fixed, it was added the value "amazon" to the case block on the default attribute file, where it is defined the service name for sshd.
=> Fix to Issue #180. Cookbook fails on Amazon Linux

templates/default/opensshd.conf.erb
Extra config block needs to come before the potential SFTP Match configuration.  If SFTP is enabled, any extra configuration options fall under the match block and do not take effect.
The statement on this line is correct, Match blocks must always be at the end of the configuration file 😉  https://github.com/dev-sec/chef-ssh-hardening/blob/master/templates/default/opensshd.conf.erb#L227
=> Fix Extra Configuration

README.md, attributes/default.rb, templates/default/opensshd.conf.erb
Not much to say. I needed this, but I haven't researched the level of evilness this permits.
=> Allow password authentification for sftp

attributes/default.rb
While this cookbook isn't specific (and shouldn't be specific) to CIS Benchmarks, it's helpful as a
baseline to set the default behaviors to the recommended value. Folks can override to 600 if needed.
=> Modified the client_alive_interval default to 300

templates/default/opensshd.conf.erb
removed 2 spaces between key/value that sshd was constantly re-writing
=> minor updated to template

attributes/default.rb, templates/default/openssh.conf.erb
ForwardAgent should also be configurable for the client-side
=> Make ForwardAgent configurable for Client Configuration

libraries/devsec_ssh.rb, recipes/client.rb, spec/libraries/devsec_ssh_spec.rb, spec/recipes/client_spec.rb, templates/default/openssh.conf.erb
E.g. on Ubuntu 18.04
Fixes #195
=> Avoid some deprecated options for OpenSSH >=7.6

attributes/default.rb, templates/default/opensshd.conf.erb
Use the flexibility to change the log level for sftp subsystem
Issue #199
=> Add attribute for sftp subsystem logging

.kitchen.dokken.yml, .kitchen.yml, recipes/client.rb, recipes/server.rb, spec/recipes/server_spec.rb, templates/default/opensshd.conf.erb, test/integration/default/controls/deprecations.rb, test/integration/default/controls/ssh-baseline.rb, test/integration/default/inspec.yml
Fixes #202 
Please see the https://github.com/dev-sec/ssh-baseline/pull/114 and https://github.com/dev-sec/ssh-baseline/pull/116 too
=> Removal of deprecated options for newer openssh versions

README.md
- Removal of gemnaisum badge
- Use the CI badge from master branch only but not from the any last build
Signed-off-by: Artem Sidorenko <artem@posteo.de>
=> Update of badges in README

spec/recipes/client_spec.rb, spec/recipes/default_spec.rb, spec/recipes/server_spec.rb, spec/recipes/unlock_spec.rb
It should consume less resources and be faster
Signed-off-by: Artem Sidorenko <artem@posteo.de>
=> Tests: try to use SoloRunner instead of ServerRunner

.kitchen.dokken.yml, .kitchen.yml, .travis.yml, README.md
Signed-off-by: Artem Sidorenko <artem@posteo.de>
=> Updating supported fedora versions and include Fedora 30

.rubocop.yml, README.md, attributes/default.rb, spec/recipes/server_spec.rb, templates/default/opensshd.conf.erb
They are sometimes useful when you need to have user/group rectrictions or want to override some global configuration options
Signed-off-by: Artem Sidorenko <artem.sidorenko@t-systems.com>
=> Support of custom match configuration blocks

README.md, attributes/default.rb, spec/recipes/server_spec.rb, templates/default/opensshd.conf.erb
Since OpenSSH OpenSSH 5.6 (2010-08-23), one can specify an AuthorizedKeysFile parameter inside the Match block.
I didn't add any test because I don't think rspec can handle multiple parameters (the global one & the Match one).
=> Allow to specify an alternate AuthorizedKeysFile inside the Match block

.travis.yml, attributes/default.rb, recipes/server.rb
there is a difference between rhel 8 and before
Signed-off-by: Artem Sidorenko <artem.sidorenko@t-systems.com>
=> CentOS 8: proper selinux package naming

attributes/default.rb
Simple change to add support for CentOS 8 alternatives Rocky Linux and Almalinux
Ref: https://docs.chef.io/infra_language/checking_platforms/
=> add centos 8 alt platforms - rocky, almalinux
